version: '3.7'

services:
    {{cookiecutter.service_name}}:
        build:
            context: .
            dockerfile: Dockerfile
        image: {{cookiecutter.service_name}}
        ports:
            - "{{cookiecutter.service_port}}:{{cookiecutter.service_port}}"
        environment:
            - {{cookiecutter.service_name.upper()}}__LOGGER__PATH="/var/log/{{cookiecutter.service_name}}"
            - {{cookiecutter.service_name.upper()}}__LOGGER__FILENAME="service.log"
            - {{cookiecutter.service_name.upper()}}__SERVICE__MODE="prod"
            - {{cookiecutter.service_name.upper()}}__SERVICE__PORT={{cookiecutter.service_port}}
        volumes:
            - type: bind
              source: "/var/log/{{cookiecutter.service_name}}"
              target: "/var/log/{{cookiecutter.service_name}}"
