version: '3.7'

services:
    <SERVICENAME>:
        build:
            context: .
            dockerfile: Dockerfile
        image: <SERVICENAME>
        ports:
            - "<SERVICE_PORT>:80"
        environment:
            - <SERVICENAME>_SERVICE__MODE="prod"
            - ...
        volumes:
            - type: bind
              source: <LOGFOLDER_ON_HOST>
              target: <LOGFOLDER_INSIDE_DOCKER_CONTAINER>
