service:
    name: '{{cookiecutter.service_name}}'
    mode: 'devl'
    port: {{cookiecutter.service_port}}
    description: ''
    apidoc_dir: 'docs/_build/site'
    readme: 'README.md'
    allowed_hosts:
        - '*'
    use_default_endpoints:
        - alive
        - config
external_resources: {}
logger:
    path: './log/{{cookiecutter.service_name}}'
    filename: 'service_{mode}.log'
    level: 'debug'
    rotation: '1 days'
    retention: '1 months'
    format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> [id: {extra[request_id]}] - <level>{message}</level>"

available_environment_variables:
    env_vars:
        - {{cookiecutter.service_name.upper()}}__SERVICE__MODE
        - {{cookiecutter.service_name.upper()}}__SERVICE__PORT
        - {{cookiecutter.service_name.upper()}}__LOGGER__LEVEL
        - {{cookiecutter.service_name.upper()}}__LOGGER__PATH
        - {{cookiecutter.service_name.upper()}}__LOGGER__FILENAME
        - {{cookiecutter.service_name.upper()}}__LOGGER__ROTATION
        - {{cookiecutter.service_name.upper()}}__LOGGER__RETENTION
        - {{cookiecutter.service_name.upper()}}__LOGGER__FORMAT
    external_resources_env_vars: []
    rules_env_vars: []
