service:
    name: '{{cookiecutter.service_name}}'
    mode: 'devl'
    development_port: {{cookiecutter.service_port}}
    description: ''
    apidoc_dir: 'docs/_build'
    readme: 'README.md'
    allowed_hosts:
        - '*'
    use_prometheus: {{cookiecutter.use_prometheus}}
    use_default_endpoints:
        - alive
        - config
external_resources: {}
logger:
    path: './log/{{cookiecutter.service_name}}'
    filename: 'service_{mode}.log'
    level: 'debug'
    rotation: '1 days'
    retention: '1 months'
    format: '{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}'
available_environment_variables:
    env_vars:
        - SERVICE__MODE
        - SERVICE__DEVELOPMENT_PORT
        - LOGGER__LEVEL
        - LOGGER__PATH
        - LOGGER__FILENAME
        - LOGGER__ROTATION
        - LOGGER__RETENTION
        - LOGGER__FORMAT
    external_resources_env_vars: []
    rules_env_vars: []
